/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSlotsRouteImport } from './routes/_dashboard/slots'
import { Route as DashboardPrescriptionsRouteImport } from './routes/_dashboard/prescriptions'
import { Route as DashboardPatientsRouteImport } from './routes/_dashboard/patients'
import { Route as DashboardMedicalRecordsRouteImport } from './routes/_dashboard/medical-records'
import { Route as DashboardAppointmentsRouteImport } from './routes/_dashboard/appointments'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlotsRoute = DashboardSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrescriptionsRoute = DashboardPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMedicalRecordsRoute = DashboardMedicalRecordsRouteImport.update({
  id: '/medical-records',
  path: '/medical-records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/appointments': typeof DashboardAppointmentsRoute
  '/medical-records': typeof DashboardMedicalRecordsRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/slots': typeof DashboardSlotsRoute
}
export interface FileRoutesByTo {
  '/appointments': typeof DashboardAppointmentsRoute
  '/medical-records': typeof DashboardMedicalRecordsRoute
  '/patients': typeof DashboardPatientsRoute
  '/prescriptions': typeof DashboardPrescriptionsRoute
  '/slots': typeof DashboardSlotsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/appointments': typeof DashboardAppointmentsRoute
  '/_dashboard/medical-records': typeof DashboardMedicalRecordsRoute
  '/_dashboard/patients': typeof DashboardPatientsRoute
  '/_dashboard/prescriptions': typeof DashboardPrescriptionsRoute
  '/_dashboard/slots': typeof DashboardSlotsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/medical-records'
    | '/patients'
    | '/prescriptions'
    | '/slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/appointments'
    | '/medical-records'
    | '/patients'
    | '/prescriptions'
    | '/slots'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/appointments'
    | '/_dashboard/medical-records'
    | '/_dashboard/patients'
    | '/_dashboard/prescriptions'
    | '/_dashboard/slots'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/slots': {
      id: '/_dashboard/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof DashboardSlotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prescriptions': {
      id: '/_dashboard/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof DashboardPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/patients': {
      id: '/_dashboard/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/medical-records': {
      id: '/_dashboard/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof DashboardMedicalRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments': {
      id: '/_dashboard/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardMedicalRecordsRoute: typeof DashboardMedicalRecordsRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardPrescriptionsRoute: typeof DashboardPrescriptionsRoute
  DashboardSlotsRoute: typeof DashboardSlotsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardMedicalRecordsRoute: DashboardMedicalRecordsRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardPrescriptionsRoute: DashboardPrescriptionsRoute,
  DashboardSlotsRoute: DashboardSlotsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
